# application-mybatis-dev.yml：开发环境
# application-test.yml：测试环境
# application-prod.yml：生产环境
#至于哪个具体的配置文件会被加载，需要在application.yml文件中通过spring.profiles.active属性来设置，其值对应{profile}值。
spring:
  profiles:
    active: jdbc-dev